"""Clearance packet export — the artefact counsel actually reads."""

from __future__ import annotations

from .models import Project

_COLOR_LABEL = {
    "red": "🔴 UNRESOLVED",
    "amber": "🟠 EVIDENCE INCOMPLETE",
    "blue": "🔵 COORDINATOR VERIFIED",
    "green": "🟢 DOCUMENTED",
    "gray": "⚪ DISMISSED",
}

_PROVENANCE_LABEL = {
    "cut_only": "**UNSCRIPTED** — entered through the filmed material",
    "both": "In script and cut",
    "script_only": "In script only",
}


def to_markdown(project: Project) -> str:
    summary = project.summary()
    colors = summary["colors"]
    recon = summary["reconciliation"]

    lines = [
        f"# Clearance Research Packet — {project.title}",
        "",
        f"*Generated by Clearance Radar on {project.updated_at}*",
        "",
        "> **This is clearance research, not legal advice, and nothing here is a "
        "legal clearance.** Every factual claim links to the public source it came "
        "from and the date it was retrieved. Ownership shown is a *candidate* "
        "derived from public information and must be confirmed before reliance. "
        "Legal conclusions belong to production counsel.",
        "",
        "| | |",
        "|---|---|",
        f"| Script version | `{project.script.label if project.script else '—'}` |",
        f"| Cut version | `{project.cut.label if project.cut else '—'}` |",
        f"| Clearance items | {summary['total_items']} |",
        f"| **Unscripted items** | **{summary['unscripted_items']}** |",
        f"| Sources cited | {summary['total_citations']} |",
        f"| Resolved by a human | {summary['resolved_items']} |",
        f"| **AI-issued approvals** | **{summary['ai_issued_approvals']}** |",
        "",
        "### Status",
        "",
        f"- 🔴 Unresolved: {colors['red']}",
        f"- 🟠 Evidence incomplete: {colors['amber']}",
        f"- 🔵 Coordinator verified: {colors['blue']}",
        f"- 🟢 Documented: {colors['green']}",
        f"- ⚪ Dismissed: {colors['gray']}",
        "",
        "### Script-to-cut reconciliation",
        "",
        f"- In both: {recon['in_both']}",
        f"- Script only: {recon['script_only']}",
        f"- **Cut only (unscripted): {recon['cut_only']}**",
        f"- Materially changed: {recon['materially_changed']}",
        "",
        "---",
        "",
    ]

    for item in project.items:
        label = _COLOR_LABEL.get(item.color, item.color.upper())
        lines.append(f"## {label} — {item.name}")
        lines.append("")
        lines.append(
            f"**Category:** {item.category} · **Status:** `{item.workflow_status}` · "
            f"**Detection confidence:** {item.detection_confidence} · "
            f"**Priority:** {item.research_priority}"
        )
        lines.append("")
        lines.append(_PROVENANCE_LABEL.get(item.provenance, item.provenance))
        lines.append("")

        if item.description:
            lines.append(item.description)
            lines.append("")

        if item.cut_detections:
            lines.append("### On screen")
            lines.append("")
            for detection in item.cut_detections:
                lines.append(
                    f"- `{detection.timecode.label()}` ({detection.modality}) — "
                    f"{detection.observation}"
                )
            lines.append("")

        if item.script_references:
            lines.append("### In the script")
            lines.append("")
            for ref in item.script_references:
                page = f"p. {ref.page}" if ref.page else "page unknown"
                lines.append(
                    f"- **Scene {ref.scene_index}** — {ref.scene_heading} ({page}) — "
                    f"{ref.usage_note}"
                )
                excerpt = ref.excerpt.strip().replace("\n", " ")
                if excerpt:
                    lines.append(f"  > {excerpt}")
            lines.append("")

        if item.candidate_rights_holders:
            lines.append("### Candidate rights holders")
            lines.append("")
            lines.append("| Name | Role | Rights | Share | Confidence |")
            lines.append("|---|---|---|---|---|")
            for holder in item.candidate_rights_holders:
                rights = ", ".join(holder.rights_implicated) or "—"
                lines.append(
                    f"| {holder.name} | {holder.role} | {rights} | "
                    f"{holder.share or '—'} | {holder.confidence} |"
                )
            lines.append("")
            lines.append("*Candidates derived from public sources — confirm before reliance.*")
            lines.append("")

        if item.licensing_routes:
            lines.append("### Licensing routes")
            lines.append("")
            for route in item.licensing_routes:
                target = f"[{route.organization}]({route.url})" if route.url else route.organization
                lines.append(f"- **{target}** — {route.route}")
                if route.contact:
                    lines.append(f"  - Contact: {route.contact}")
            lines.append("")

        if item.research_summary:
            lines.append("### Research summary")
            lines.append("")
            lines.append(item.research_summary)
            lines.append("")

        if item.evidence_gaps:
            lines.append("### Evidence gaps")
            lines.append("")
            for gap in item.evidence_gaps:
                lines.append(f"- {gap}")
            lines.append("")

        if item.unresolved_questions:
            lines.append("### Unresolved questions")
            lines.append("")
            for question in item.unresolved_questions:
                lines.append(f"- {question}")
            lines.append("")

        if item.recommended_actions:
            lines.append("### Recommended next actions")
            lines.append("")
            for index, action in enumerate(item.recommended_actions, start=1):
                lines.append(f"{index}. {action}")
            lines.append("")

        if item.documents:
            lines.append("### Attached documents")
            lines.append("")
            for document in item.documents:
                lines.append(
                    f"- **{document.kind}** — {document.title} "
                    f"(territory: {document.covers_territory or '—'}, "
                    f"term: {document.covers_term or '—'}, "
                    f"media: {document.covers_media or '—'})"
                )
            lines.append("")

        if item.sources:
            lines.append(f"### Sources — {item.citation_count}")
            lines.append("")
            seen: set[str] = set()
            for source in item.sources:
                if source.url in seen:
                    continue
                seen.add(source.url)
                title = source.title or source.url
                lines.append(
                    f"- [{title}]({source.url}) — *via {source.via.replace('_', ' ')}, "
                    f"retrieved {source.retrieved_at[:10]}*"
                )
                if source.excerpt:
                    lines.append(f"  > {source.excerpt.strip()[:280]}")
            lines.append("")
        else:
            lines.append("### Sources")
            lines.append("")
            lines.append("- *No public sources retrieved. This item is unresolved.*")
            lines.append("")

        if item.audit_events:
            lines.append("<details><summary>Audit trail</summary>")
            lines.append("")
            lines.append("| When | Actor | Action | From → To | Rationale |")
            lines.append("|---|---|---|---|---|")
            for event in item.audit_events:
                transition = (
                    f"{event.from_status or '—'} → {event.to_status or '—'}"
                    if event.to_status
                    else "—"
                )
                lines.append(
                    f"| {event.at[:19]} | {event.actor}"
                    f"{f' ({event.actor_name})' if event.actor_name else ''} "
                    f"| {event.action} | {transition} | {event.rationale} |"
                )
            lines.append("")
            lines.append("</details>")
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)
